[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deep-translator>=1.11.4",
    "flask>=3.1.0",
    "gtts>=2.5.4",
    "pypinyin>=0.53.0",
    "requests>=2.32.3",
]
